sudo: required
services:
  - docker

before_install:
  - docker build -t angtb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true angtb/react-test npm test

after_success:
  - docker build -t angtb/multi-client ./client
  - docker build -t angtb/multi-nginx ./nginx
  - docker build -t angtb/multi-server ./server
  - docker build -t angtb/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images to docker hub
  - docker push angtb/multi-client
  - docker push angtb/multi-nginx
  - docker push angtb/multi-server
  - docker push angtb/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker1
  env: Multidocker1-env
  bucket_name: elasticbeanstalk-us-east-2-420253496884
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  


